Add Acic data generating processes + raw data
theo-s/bart-sims pull request #5
Opened 2023-01-27 03:37 UTC by theo-s

2023-01-27 21:44 UTC, OmerRonen requested changes
@theo-s great work! thanks for doing this so fast, I left a few comments. The main issue is to validate that the CLI works with the new dgps

2023-01-27 21:44 UTC, OmerRonen commented on code/bart_stability.R
> +  data_train <- data[1:train_n,-which(colnames(data) == "Ytrue")]
@theo-s why not take the test set as a random? Looking at the data it seems like similar outcomes are clustered together

2023-01-27 21:44 UTC, OmerRonen commented on code/bart_stability.R
> +  colnames(data_train)[which(colnames(data_train) == "Y")] <- "y"
The columns names create a bug with bart_fit, could you please make sure the columns names are the same for train and test? Also could you please check that the CLI works using acic arguments?

2023-01-27 21:44 UTC, OmerRonen commented on code/bart_stability.R
>  get_data <- function(dgp,n, q, rho=0.05, seed=0){
Please generalize this function to include acic dgps, you can set a default value for q if that is a problem

2023-01-30 21:28 UTC, theo-s commented
In the last commit I changed the version of the ACIC 2019 data to use one with continuous outcomes rather than binary outcomes as this was giving BART some problems when it was asked to train on binary features and then calculate RMSE with probabilities. It makes more sense to just use the continuous outcomes. Unfortunately this version only has 500 observations, so will probably be pretty small for any analysis

2023-01-30 21:30 UTC, theo-s commented
The CLI is now working as well, although given the size of the data, the range of `n` used in `bart_stablity.R` should be modified before running these dgps

2023-01-30 22:45 UTC, merged